export enum UserModule {
  CONTAS_PAGAR = 'CONTAS_PAGAR',
  ESTOQUE = 'ESTOQUE',
  MOVIMENTACOES = 'MOVIMENTACOES',
  RELATORIOS = 'RELATORIOS',
  USUARIOS = 'USUARIOS',
  DASHBOARD = 'DASHBOARD',
  FORNECEDORES = 'FORNECEDORES',
  CATEGORIAS = 'CATEGORIAS',
  CONTATOS = 'CONTATOS',
  RELATORIO_CONTAS_PAGAR = 'RELATORIO_CONTAS_PAGAR',
}
