export enum UserModule {
  CONTAS_PAGAR = 'CONTAS_PAGAR',
  RELATORIO_CONTAS_PAGAR = 'RELATORIO_CONTAS_PAGAR',
  ESTOQUE = 'ESTOQUE',
  MOVIMENTACOES = 'MOVIMENTACOES',
  RELATORIOS = 'RELATORIOS',
  FORNECEDORES = 'FORNECEDORES',
  CATEGORIAS = 'CATEGORIAS',
  DASHBOARD = 'DASHBOARD',
  CONTATOS = 'CONTATOS',
  USUARIOS = 'USUARIOS',
  DESPESAS_VIAGEM = 'DESPESAS_VIAGEM',
}
